# Generated by Django 4.1.5 on 2023-01-20 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('lore', models.TextField(verbose_name='История')),
                ('strength', models.IntegerField(verbose_name='Сила')),
                ('agility', models.IntegerField(verbose_name='Ловкость')),
                ('intellect', models.IntegerField(verbose_name='Интеллект')),
            ],
        ),
        migrations.CreateModel(
            name='HeroClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('descr', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('descr', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('descr', models.TextField(blank=True, verbose_name='Описание')),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('N', 'Not so common'), ('R', 'Actually, rare'), ('L', "Freakin'Legendary")], max_length=1, verbose_name='Рарность')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.hero', verbose_name='Владелец')),
                ('weapon_category', models.ForeignKey(default='Валына', on_delete=django.db.models.deletion.SET_DEFAULT, to='items.weapon', verbose_name='Класс оружия')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_class',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.heroclass', verbose_name='Класс героя'),
        ),
        migrations.AddField(
            model_name='hero',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-владелец'),
        ),
    ]
