# Generated by Django 4.1.5 on 2023-01-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Титул/прозвище'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weapon_category',
            field=models.ForeignKey(default='Неизвестная валына', on_delete=django.db.models.deletion.SET_DEFAULT, to='items.weapon', verbose_name='Класс оружия'),
        ),
    ]
