# Generated by Django 4.1.5 on 2023-01-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_hero_name_alter_hero_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='agility',
            field=models.IntegerField(blank=True, verbose_name='Ловкость'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='intellect',
            field=models.IntegerField(blank=True, verbose_name='Интеллект'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='lore',
            field=models.TextField(blank=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength',
            field=models.IntegerField(blank=True, verbose_name='Сила'),
        ),
    ]
