# Generated by Django 4.1.5 on 2023-01-21 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_alter_hero_agility_alter_hero_intellect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-владелец'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weapon_category',
            field=models.ForeignKey(default='Неизвестная валына', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='items.weapon', verbose_name='Класс оружия'),
        ),
    ]
