# Generated by Django 4.1.5 on 2023-01-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rename_username_hero_owner_hero_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Not so common', 'Not so common'), ('Actually, rare', 'Actually, rare'), ("Freakin'Legendary", "Freakin'Legendary")], max_length=20, verbose_name='Рарность'),
        ),
    ]
