# Generated by Django 4.1.5 on 2023-01-24 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0006_alter_item_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-владелец'),
        ),
    ]
